MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    STRIDE_IN_1X1: False
    BACKBONE_OUT_CHANNELS: 256
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    STAGE_WITH_DCN: (False, False, True, True)
    WITH_MODULATED_DCN: True
    DEFORMABLE_GROUPS: 1
  RETINANET:
    USE_C5: False
  FCOS:
    # normalizing the regression targets with FPN strides
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_test_dev",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (480, 960)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 16
  WARMUP_METHOD: "constant"
# TEST:
#   BBOX_AUG:
#     ENABLED: False
#     H_FLIP: True
#     SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)
#     MAX_SIZE: 2000
#     SCALE_H_FLIP: True
